// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Capabilities reports what the active backend can do, for the UI.
 */
export interface Capabilities {
    "Backend": string;
    "FallbackReason": string;
    "CanReadCursor": boolean;
    "CanPickPoint": boolean;
    "CanEnumerateDisplays": boolean;
    "CanMoveAbsolute": boolean;
}

/**
 * Display is one monitor in physical pixels of the virtual desktop.
 */
export interface Display {
    "X": number;
    "Y": number;
    "W": number;
    "H": number;
    "Scale": number;
    "Primary": boolean;
}
