// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Progress is the event payload pushed to the UI (DESIGN §4.2).
 */
export interface Progress {
    "state": State;
    "profileName": string;
    "moduleId": string;
    "moduleLabel": string;
    "moduleIndex": number;
    "moduleTotal": number;
    "clickIndex": number;
    "clickTotal": number;
    "loopIteration": number;
    "clicks": number;
    "elapsedMs": number;
    "stopReason"?: string;
    "error"?: string;
}

/**
 * State is the runner state.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateIdle = "idle",
    StateRunning = "running",
    StatePaused = "paused",
    StateStopping = "stopping",
};
