// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Issue is one validation finding, addressable to a module/field so the UI can
 * render it next to the offending control.
 */
export interface Issue {
    "level": IssueLevel;
    "moduleId"?: string;
    "field"?: string;
    "message": string;
}

/**
 * IssueLevel distinguishes a run blocker from an advisory warning.
 */
export enum IssueLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Blocking = "blocking",
    Warning = "warning",
};

/**
 * Profile is one .json file; the filename (without extension) is the profile id.
 */
export type Profile = any;
