// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as input$0 from "../input/models.js";

/**
 * Diagnostics is the support payload (DESIGN §5.5).
 */
export interface Diagnostics {
    "version": string;
    "robotgoPin": string;
    "appId": string;
    "backend": string;
    "fallbackReason"?: string;
    "canReadCursor": boolean;
    "canPickPoint": boolean;
    "canMoveAbsolute": boolean;
    "desktopWidth": number;
    "desktopHeight": number;
    "displays": input$0.Display[] | null;
    "hotkeySource": string;
    "hotkeyError"?: string;
    "profilesDir": string;
    "logDir": string;
}
