// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the app's operation surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as input$0 from "../input/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelPick abandons the countdown (Esc / cancel button while the app is focused).
 */
export function CancelPick(): $CancellablePromise<void> {
    return $Call.ByID(3660676554);
}

/**
 * Capabilities reports the active backend's feature set.
 */
export function Capabilities(): $CancellablePromise<input$0.Capabilities> {
    return $Call.ByID(2856468939);
}

/**
 * CloseHotkeys releases the global shortcuts.
 */
export function CloseHotkeys(): $CancellablePromise<void> {
    return $Call.ByID(2916015802);
}

/**
 * ConfirmPick captures immediately (Enter in the app, or a "capture now" button).
 */
export function ConfirmPick(): $CancellablePromise<void> {
    return $Call.ByID(3460151822);
}

/**
 * CreateProfile creates a profile from the first-run template.
 */
export function CreateProfile(name: string): $CancellablePromise<string> {
    return $Call.ByID(3589420026, name);
}

/**
 * CursorPos returns the real pointer position when available.
 */
export function CursorPos(): $CancellablePromise<[number, number, boolean]> {
    return $Call.ByID(914760419);
}

/**
 * DeleteProfile removes a profile.
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2929884099, id);
}

/**
 * Diagnostics assembles the support payload.
 */
export function Diagnostics(): $CancellablePromise<$models.Diagnostics> {
    return $Call.ByID(2171769019);
}

/**
 * Displays enumerates monitors for the picker.
 */
export function Displays(): $CancellablePromise<input$0.Display[] | null> {
    return $Call.ByID(1480618950);
}

/**
 * DuplicateProfile copies a profile.
 */
export function DuplicateProfile(id: string): $CancellablePromise<string> {
    return $Call.ByID(321938359, id);
}

/**
 * GetSettings returns the current settings.
 */
export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(3853078054);
}

/**
 * HotkeySourceName reports the active mechanism for diagnostics.
 */
export function HotkeySourceName(): $CancellablePromise<string> {
    return $Call.ByID(1166970513);
}

/**
 * ListProfiles returns readable profiles and unparseable files.
 */
export function ListProfiles(): $CancellablePromise<[store$0.Summary[] | null, store$0.ProblemFile[] | null]> {
    return $Call.ByID(735307495);
}

/**
 * LoadProfile loads one profile.
 */
export function LoadProfile(id: string): $CancellablePromise<model$0.Profile | null> {
    return $Call.ByID(2671609438, id);
}

/**
 * OpenLogDir opens the log folder in the OS file manager.
 */
export function OpenLogDir(): $CancellablePromise<void> {
    return $Call.ByID(1142218816);
}

/**
 * OpenProfilesDir opens the profiles folder in the OS file manager.
 */
export function OpenProfilesDir(): $CancellablePromise<void> {
    return $Call.ByID(711142118);
}

/**
 * Panic aborts immediately and releases inputs.
 */
export function Panic(): $CancellablePromise<void> {
    return $Call.ByID(3125584712);
}

/**
 * Pause pauses the run.
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(1861291705);
}

/**
 * ProfilesDir returns the resolved profiles folder.
 */
export function ProfilesDir(): $CancellablePromise<string> {
    return $Call.ByID(3059552250);
}

/**
 * RegisterHotkeys binds the configured global shortcuts. It may block on a
 * portal consent dialog, so callers should run it off the UI thread.
 */
export function RegisterHotkeys(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1139175487);
}

/**
 * RenameProfile renames a profile and its file, returning the new id.
 */
export function RenameProfile(id: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(970090216, id, newName);
}

/**
 * Resume resumes the run.
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(3690336990);
}

/**
 * Run starts the given profile.
 */
export function Run(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3921196742, profileID);
}

/**
 * SaveProfile writes a profile and remembers it as selected.
 */
export function SaveProfile(id: string, p: model$0.Profile | null): $CancellablePromise<void> {
    return $Call.ByID(1430973913, id, p);
}

/**
 * SaveSettings persists settings.
 */
export function SaveSettings(st: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(3769022993, st);
}

/**
 * StartPick begins a countdown and returns immediately. After PickCountdown the
 * real cursor position is captured and delivered via the PickDone callback
 * (`pick:done`). There is no second window: the countdown is shown inside the
 * app, which sidesteps Wayland's window positioning/focus/transparency limits.
 */
export function StartPick(): $CancellablePromise<void> {
    return $Call.ByID(3720731886);
}

/**
 * Status returns the latest progress.
 */
export function Status(): $CancellablePromise<engine$0.Progress> {
    return $Call.ByID(921893019);
}

/**
 * Stop requests a graceful stop.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(565513769);
}

/**
 * UpdateDisplaySnapshot refreshes a profile's display geometry.
 */
export function UpdateDisplaySnapshot(id: string): $CancellablePromise<void> {
    return $Call.ByID(1248690842, id);
}

/**
 * Validate returns the same issues the runner would refuse on.
 */
export function Validate(p: model$0.Profile | null): $CancellablePromise<model$0.Issue[] | null> {
    return $Call.ByID(3788850983, p);
}

/**
 * Version returns the embedded app version.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2216520035);
}
