// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProblemFile is a .json file that could not be parsed.
 */
export interface ProblemFile {
    "id": string;
    "error": string;
}

/**
 * Settings is the machine-specific app configuration (DESIGN §3.10).
 */
export type Settings = any;

/**
 * Summary describes a profile without loading all of it.
 */
export interface Summary {
    "id": string;
    "name": string;
    "modules": number;
    "enabled": number;
}
